[book]
title = "Cashier"
authors = ["Alen Šiljak"]
description = "Cashier documentation"
src = "src"
language = "en"
text-direction = "ltr"

#[build]
#build-dir = "docs"

[output.html]
default-theme = "Ayu"
preferred-dark-theme = "Ayu"
